services:
  server:
    container_name: "TodoAPI-Server"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:88"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    container_name: "TodoAPI-DB"
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=TodoAPI
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_DB=TodoAPI
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U TodoAPI"]
      interval: 2s
      timeout: 1s
      retries: 5
    env_file:
      - .env
  redis:
    container_name: "TodoAPI-Redis"
    image: redis:7.4-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass q2sewFemD4BRynbCXLfbG88q06SuAwKL # since the redis container isn't exposed, this should be fine. change anyways for better security
    volumes: 
      - redis_data:/data

volumes:
  pg_data:
  redis_data: